Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "orderId"
          "AttributeType": "S"
        - "AttributeName": "status"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "orderId"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "Orders"
      GlobalSecondaryIndexes:
        - IndexName: "StatusIndex"
          KeySchema:
            - AttributeName: "status"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: dynamodbAccessRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
  InitFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          const AWS = require("aws-sdk");
          const response = require('./cfn-response');
          const docClient = new AWS.DynamoDB.DocumentClient();
          exports.handler = function(event, context) {
            console.log(JSON.stringify(event,null,2));
            var params = {
              RequestItems: {
                "Orders": [
                  {
                    PutRequest: {
                      Item: {
                        orderId: "order001" ,
                        name: "test order" ,
                        phone: "1234567890" ,
                        menuItems: ["ljn643"],
                        status: "READY" ,
                        total: 7.5,
                        orderDate: "2022-06-01T17:42:34Z",
                        updateDate: "2022-06-01T18:25:48Z"
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        orderId: "order002" ,
                        name: "test order" ,
                        phone: "1234567890" ,
                        menuItems: ["ljn643", "ibr930", "ibr930"],
                        status: "READY" ,
                        total: 24.5,
                        orderDate: "2022-06-03T17:42:34Z",
                        updateDate: "2022-06-03T18:25:48Z"
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        orderId: "order003" ,
                        name: "Bob Brown" ,
                        phone: "0987654321" ,
                        menuItems: ["ljn643", "ibr930", "ibr930", "uge450"],
                        status: "READY" ,
                        total: 32,
                        orderDate: "2022-05-03T17:42:34Z",
                        updateDate: "2022-05-03T18:25:48Z"
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        orderId: "order004" ,
                        name: "Bob Brown" ,
                        phone: "0987654321" ,
                        menuItems: ["uge450"],
                        status: "IN_PROCESS" ,
                        total: 7.5,
                        orderDate: "2022-05-01T15:42:34Z",
                        updateDate: "2022-05-01T16:25:48Z"
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        orderId: "order005" ,
                        name: "name" ,
                        phone: "1111122222" ,
                        menuItems: ["ljn643"],
                        status: "RECEIVED" ,
                        total: 7.5,
                        orderDate: "2022-06-14T15:42:34Z",
                        updateDate: "2022-06-14T15:42:34Z"
                      }
                    }
                  }
                ]
              }
            };
            docClient.batchWrite(params, function(err, data) {
              if (err) {
                response.send(event, context, "FAILED", {});
              } else {
                response.send(event, context, "SUCCESS", {});
              }
            });
          };
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , "Arn" ]
      # 2020-02-27: [bp] updated from nodejs10.x in case it matters
      Runtime: nodejs12.x
      Timeout: 60
  InitializeEventsTable:
    Type: Custom::InitFunction
    DependsOn: OrdersTable
    Properties:
      ServiceToken:
        Fn::GetAtt: [ InitFunction , "Arn" ]
      DynamoTableName:
        Ref: OrdersTable
